"""empty message

Revision ID: cf3bec64757f
Revises: c415b7ce5182
Create Date: 2021-03-23 23:30:08.560160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3bec64757f'
down_revision = 'c415b7ce5182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('spaces', sa.Integer(), nullable=True))
    op.drop_column('properties', 'rooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('rooms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('properties', 'spaces')
    # ### end Alembic commands ###
